# Generated by Django 2.2.22 on 2021-05-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_education_exprience'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exprience',
            new_name='Experience',
        ),
    ]
